/**
 * Generator matrix G and parity-check matrix H for the cyclic code generated by g(x).
 *
 * An (n, k) cyclic code with generator g(x) of degree r = n − k has two standard bases:
 *
 *   Non-systematic  row i = g(x)·x^(k−1−i).  Every row is a shift of g(x), which is why
 *                   the code is "cyclic". Encoding is a plain polynomial multiply, but the
 *                   message is not visible in the codeword.
 *
 *   Systematic      G = [I_k | P], where row i of P is x^(n−1−i) mod g(x). This is the form
 *                   CRC actually uses: the codeword is the message followed by the FCS.
 *
 * The systematic rows come straight from `polyDivideSteps`, so the derivation reuses the
 * same long-division trace the CRC page renders.
 */

import {
  weight,
  type Bit,
  type Bits,
  type DivisionResult,
  polyDivideSteps,
  polyMul,
  padLeft,
  xPow,
  normalize,
  isZero,
  bitsToString,
  formatAlgebraic,
} from './gf2';

export type Matrix = Bits[];

/* ------------------------------------------------------------------ *
 * Matrix helpers over GF(2)
 * ------------------------------------------------------------------ */

export function transpose(m: Matrix): Matrix {
  if (m.length === 0) return [];
  return m[0].map((_, col) => m.map((row) => row[col]));
}

/** Matrix product over GF(2): multiply is AND, add is XOR. */
export function matMul(a: Matrix, b: Matrix): Matrix {
  if (a.length === 0 || b.length === 0) return [];
  if (a[0].length !== b.length) {
    throw new Error(`Cannot multiply ${a.length}x${a[0].length} by ${b.length}x${b[0].length}`);
  }
  return a.map((row) =>
    b[0].map((_, j) => {
      let acc: Bit = 0;
      for (let k = 0; k < b.length; k++) acc = (acc ^ (row[k] & b[k][j])) as Bit;
      return acc;
    }),
  );
}

export function isZeroMatrix(m: Matrix): boolean {
  return m.every((row) => row.every((b) => b === 0));
}

/* ------------------------------------------------------------------ *
 * Derivation
 * ------------------------------------------------------------------ */

export interface SystematicRowDerivation {
  /** Row index, 0-based from the top. */
  row: number;
  /** The dividend x^(n−1−i), as an exponent and as bits. */
  exponent: number;
  dividend: Bits;
  /** The r-bit remainder that becomes this row's parity portion. */
  remainder: Bits;
  /** Full division trace for this row. */
  division: DivisionResult;
  /** The finished row: e_i followed by the remainder. */
  fullRow: Bits;
  /** Prose for the UI. */
  note: string;
}

export interface NonSystematicRowDerivation {
  row: number;
  /** g(x) is shifted left by this many positions. */
  shift: number;
  fullRow: Bits;
  note: string;
}

export interface GeneratorMatrixResult {
  n: number;
  k: number;
  r: number;
  generator: Bits;
  generatorAlgebraic: string;

  nonSystematic: Matrix;
  nonSystematicSteps: NonSystematicRowDerivation[];

  systematic: Matrix;
  systematicSteps: SystematicRowDerivation[];
  /** The parity portion P (k x r) of the systematic G. */
  parity: Matrix;

  /** H = [Pᵀ | I_r], r x n. */
  parityCheck: Matrix;
  /** G·Hᵀ, which must be the k x r zero matrix. */
  product: Matrix;
  valid: boolean;
}

/**
 * Build both forms of G, plus H, plus the G·Hᵀ = 0 self-check.
 *
 * `k` is the message length; n = k + r follows from the generator's degree.
 */
export function buildGeneratorMatrix(generator: Bits, k: number): GeneratorMatrixResult {
  const g = normalize(generator);
  if (isZero(g)) throw new Error('Generator polynomial cannot be zero');
  const r = g.length - 1;
  if (r < 1) throw new Error('Generator polynomial must have degree >= 1');
  if (!Number.isInteger(k) || k < 1) throw new Error(`k must be a positive integer, got ${k}`);
  const n = k + r;

  // --- Non-systematic: each row is g(x) shifted -------------------------------
  const nonSystematicSteps: NonSystematicRowDerivation[] = [];
  const nonSystematic: Matrix = [];
  for (let i = 0; i < k; i++) {
    const shift = k - 1 - i;
    const row = padLeft(polyMul(g, xPow(shift)), n);
    nonSystematic.push(row);
    nonSystematicSteps.push({
      row: i,
      shift,
      fullRow: row,
      note:
        `Row ${i}: g(x)·x^${shift} = ${formatAlgebraic(polyMul(g, xPow(shift)))} ` +
        `— g(x) placed with its leading term at column ${i}.`,
    });
  }

  // --- Systematic: [I_k | P], P row i = x^(n-1-i) mod g(x) --------------------
  const systematicSteps: SystematicRowDerivation[] = [];
  const systematic: Matrix = [];
  const parity: Matrix = [];
  for (let i = 0; i < k; i++) {
    const exponent = n - 1 - i;
    const dividend = xPow(exponent);
    const division = polyDivideSteps(dividend, g);
    const remainder = padLeft(division.remainder, r);

    const unit: Bits = Array(k).fill(0) as Bits;
    unit[i] = 1;
    const fullRow: Bits = [...unit, ...remainder];

    parity.push(remainder);
    systematic.push(fullRow);
    systematicSteps.push({
      row: i,
      exponent,
      dividend,
      remainder,
      division,
      fullRow,
      note:
        `Row ${i}: message bit ${i} is x^${k - 1 - i}; shifting it up by r=${r} gives ` +
        `x^${exponent}. Dividing by g(x) leaves remainder ${bitsToString(remainder)}, ` +
        `so the row is e_${i} followed by those ${r} parity bits.`,
    });
  }

  // --- H = [Pᵀ | I_r] and the G·Hᵀ = 0 check ---------------------------------
  const parityCheck: Matrix = transpose(parity).map((row, i) => {
    const tail: Bits = Array(r).fill(0) as Bits;
    tail[i] = 1;
    return [...row, ...tail];
  });

  const product = matMul(systematic, transpose(parityCheck));

  return {
    n,
    k,
    r,
    generator: g,
    generatorAlgebraic: formatAlgebraic(g),
    nonSystematic,
    nonSystematicSteps,
    systematic,
    systematicSteps,
    parity,
    parityCheck,
    product,
    valid: isZeroMatrix(product),
  };
}

/* ------------------------------------------------------------------ *
 * Encoding and syndrome decoding
 * ------------------------------------------------------------------ */

/** Encode a k-bit message as m·G. With systematic G this equals message + CRC. */
export function encode(message: Bits, g: Matrix): Bits {
  if (message.length !== g.length) {
    throw new Error(`Message is ${message.length} bits but G has ${g.length} rows`);
  }
  return matMul([message], g)[0];
}

export interface EncodeStep {
  /** Row index of G. */
  row: number;
  /** The message bit that selects this row. */
  messageBit: Bit;
  /** The row itself. */
  rowBits: Bits;
  /** Accumulator before this row was folded in. */
  before: Bits;
  /** Accumulator after. Identical to `before` when the message bit is 0. */
  after: Bits;
  /** False when the row was skipped because its message bit is 0. */
  used: boolean;
}

export interface EncodeTrace {
  message: Bits;
  steps: EncodeStep[];
  codeword: Bits;
  /** Rows actually XORed together. */
  selectedRows: number[];
}

/**
 * Encode step by step, recording the running XOR.
 *
 * m·G over GF(2) is not really a multiplication so much as a selection: each message bit
 * either includes its row of G or does not, and the included rows are XORed together.
 * Showing that directly is far more legible than a dot-product notation.
 */
export function encodeSteps(message: Bits, g: Matrix): EncodeTrace {
  if (message.length !== g.length) {
    throw new Error(`Message is ${message.length} bits but G has ${g.length} rows`);
  }
  const width = g.length ? g[0].length : 0;
  let acc: Bits = Array(width).fill(0) as Bits;
  const steps: EncodeStep[] = [];
  const selectedRows: number[] = [];

  message.forEach((bit, i) => {
    const before = acc.slice();
    if (bit === 1) {
      acc = acc.map((b, j) => (b ^ g[i][j]) as Bit);
      selectedRows.push(i);
    }
    steps.push({
      row: i,
      messageBit: bit,
      rowBits: g[i].slice(),
      before,
      after: acc.slice(),
      used: bit === 1,
    });
  });

  return { message: message.slice(), steps, codeword: acc, selectedRows };
}

/** Syndrome s = H·cᵀ. Zero means the word is a valid codeword. */
export function syndrome(codeword: Bits, h: Matrix): Bits {
  if (h.length === 0) return [];
  if (codeword.length !== h[0].length) {
    throw new Error(`Codeword is ${codeword.length} bits but H has ${h[0].length} columns`);
  }
  return matMul(h, transpose([codeword])).map((row) => row[0]);
}

/**
 * Minimum Hamming distance, found by brute force over all 2^k − 1 nonzero messages.
 *
 * For a linear code the minimum distance equals the minimum weight of a nonzero codeword,
 * so this is exact — but it is exponential in k, hence the guard.
 */
export function minimumDistance(g: Matrix, maxK = 16): number {
  const k = g.length;
  if (k > maxK) {
    throw new Error(`Brute-force minimum distance is limited to k <= ${maxK} (got k = ${k})`);
  }
  let best = Infinity;
  for (let m = 1; m < 1 << k; m++) {
    const message: Bits = Array.from({ length: k }, (_, i) => ((m >> (k - 1 - i)) & 1) as Bit);
    const w = weight(encode(message, g));
    if (w > 0 && w < best) best = w;
  }
  return best;
}
